name: st4_tuan5_trancongmanh
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xml: ^5.3.1
  intl: ^0.18.0
  sqflite: ^2.0.0
  path_provider: ^2.0.2
  provider: ^6.0.5
  sqflite_common_ffi: any
  sqflite_common_ffi_web: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
